# https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dpipeline
# usage: tranmission
# usage: distribution
# usage: penstock

pipeline:
  man_made: pipeline
  location: overground
  substance: water
  diameter: null

# https://wiki.openstreetmap.org/wiki/Proposed_features/Pipeline_valves_proposal
valve:
  pipeline: valve
  valve: { butterfly, globe, ball }
  diameter: null
  operator: Ouray Ice Park
  ref: null
  acutator: manual
  handle: { wheel, cross, lever }
  turn_to_close: { clockwise, anti_clockwise}

attributes:
  One Head: 1
  Two Heads: 2
  Three Heads: 3
  1/2 Inch: 0.5
  1 inch: 1.0
  2 inches: 2.0
  3 inches: 3.0
  4 inches: 4.0
  5 inches: 5.0
  6 inches: 6.0
  7 inches: 7.0
  8 inches: 8.0

feature:
  name: null
  pipeline: null
  showerheads: null
  valves: null
  note: null
