[project]
name = "ODKConvert"
dynamic = "0.1.0"
description = "Convert CSV files from ODK Central to OSM format."
authors = [
    {name = "Rob Savoye", email = "rob.savoye@hotosm.org"},
]
dependencies = [
    "codetiming==1.3.2",
    "epdb==0.15.1",
    "GDAL==3.4.3",
    "geodex==0.1.2",
    "geojson==2.5.0",
    "numpy==1.22.0",
    "OSMPythonTools==0.3.5",
    "pandas==1.3.4",
    "progress==1.6",
    "py-cpuinfo==8.0.0",
    "pymbtiles==0.5.0",
    "pytest==7.0.1",
    "PyYAML==6.0",
    "qrcode==7.3.1",
    "requests==2.27.1",
    "segno==1.5.2",
    "Shapely==1.7.1",
    "xmltodict==0.12.0",
]
requires-python = ">=3.9"
readme = "README.md"
license = "GPL-3.0-only"
keywords = ["fmtm", "hot", "openstreetmap"]
classifiers = [
    "Topic :: Utilities",
    "Topic :: Scientific/Engineering :: GIS",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
]

[project.urls]
homepage = "https://github.com/hotosm/odkconvert"
documentation = "https://github.com/hotosm/odkconvert"
repository = "https://github.com/hotosm/odkconvert"

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"
