site_name: osm-fieldwork
site_description: Processing collected OpenDataKit data into OpenStreetMap format, and other utility programs for field data collection.

repo_name: "hotosm/osm-fieldwork"
repo_url: "https://github.com/hotosm/osm-fieldwork"
edit_uri: "blob/main/docs/compiled/"
site_url: "https://www.hotosm.org"

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/hotosm/"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/hotosm"
    - icon: "fontawesome/solid/globe"
      link: "https://www.hotosm.org"

plugins:
  - search

theme:
  name: material
  palette:
    scheme: default

extra_css:
  - css/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret:
      insert: false
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - pymdownx.magiclink:
      hide_protocol: true
      repo_url_shortener: true
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
